name: f2fintech
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  chat_gpt_sdk:
    git:
      url: https://github.com/iampawan/Flutter-ChatGPT.git
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  velocity_x: ^4.1.2
flutter_dotenv: ^5.1.0
http: ^1.1.0
velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/download.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/download.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/download.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/download.png" 